#!/usr/bin/env python3
"""Generate corecad_manifest.yml in the repository root.

This module is intentionally small and standalone so callers (CI or
`write_version_info.py`) can import and call `generate_manifest()`.
"""
import os
import re
import subprocess
import datetime


def generate_manifest(repo_root=None):
    repo_root = repo_root or os.getcwd()

    # read CoreCAD top-level CMakeLists
    core_cmake = ''
    try:
        with open(os.path.join(repo_root, 'CMakeLists.txt'), 'r') as f:
            core_cmake = f.read()
    except Exception:
        core_cmake = ''

    def _get(name, text):
        m = re.search(r'set\s*\(\s*' + name + r'\s+"?([^\)"\s]+)"?\s*\)', text or '')
        return m.group(1) if m else None

    core_major = _get('PACKAGE_VERSION_MAJOR', core_cmake)
    core_minor = _get('PACKAGE_VERSION_MINOR', core_cmake)
    core_patch = _get('PACKAGE_VERSION_PATCH', core_cmake)
    core_suffix = _get('PACKAGE_VERSION_SUFFIX', core_cmake)
    core_version = None
    if core_major and core_minor and core_patch:
        core_version = f"{core_major}.{core_minor}.{core_patch}"
        if core_suffix and core_suffix not in ('', '""'):
            core_version += ('-' + core_suffix) if not str(core_suffix).startswith('-') else str(core_suffix)

    # FreeCAD main CMakeLists (read from git main branch)
    try:
        freecad_cmake = subprocess.check_output(['git', 'show', 'main:CMakeLists.txt'], text=True, cwd=repo_root)
    except Exception:
        freecad_cmake = ''
    free_major = _get('PACKAGE_VERSION_MAJOR', freecad_cmake)
    free_minor = _get('PACKAGE_VERSION_MINOR', freecad_cmake)
    free_patch = _get('PACKAGE_VERSION_PATCH', freecad_cmake)
    free_suffix = _get('PACKAGE_VERSION_SUFFIX', freecad_cmake)
    free_version = None
    if free_major and free_minor and free_patch:
        free_version = f"{free_major}.{free_minor}.{free_patch}"
        if free_suffix and free_suffix not in ('', '""'):
            free_version += ('-' + free_suffix) if not str(free_suffix).startswith('-') else str(free_suffix)

    def _rev(ref):
        try:
            return subprocess.check_output(['git', 'rev-parse', '--short', ref], text=True, cwd=repo_root).strip()
        except Exception:
            return None

    core_hash = _rev('HEAD')
    free_hash = _rev('main')

    manifest_path = os.path.join(repo_root, 'corecad_manifest.yml')
    try:
        with open(manifest_path, 'w') as m:
            m.write('# CoreCAD manifest autogenerated\n')
            m.write(f"corecad_version: {core_version}\n")
            m.write('corecad_version_parts:\n')
            m.write(f"  major: {core_major}\n")
            m.write(f"  minor: {core_minor}\n")
            m.write(f"  patch: {core_patch}\n")
            m.write(f"  suffix: {core_suffix}\n")
            m.write(f"  name: CoreCAD\n")
            m.write(f"corecad_commit: {core_hash}\n")
            m.write(f"freecad_base_branch: main\n")
            m.write(f"freecad_base_version: {free_version}\n")
            m.write('freecad_base_version_parts:\n')
            m.write(f"  major: {free_major}\n")
            m.write(f"  minor: {free_minor}\n")
            m.write(f"  patch: {free_patch}\n")
            m.write(f"  suffix: {free_suffix}\n")
            m.write(f"  name: FreeCAD\n")
            m.write(f"freecad_base_commit: {free_hash}\n")
            m.write(f"generated_at: {datetime.datetime.utcnow().isoformat()}Z\n")
            m.write(f"generated_by: generate_corecad_manifest.py\n")
        print('Wrote manifest to ' + manifest_path)
    except Exception as e:
        print('Failed to write manifest: ' + str(e))


if __name__ == '__main__':
    generate_manifest()
