
blank_issues_enabled : false

contact_links:
  - name: 💬 START HERE -- CoreCAD Discussions
    url: https://github.com/CoreCAD/CoreCAD/discussions
    about: You are encouraged to discuss the problem you are seeing in CoreCAD Discussions before opening an issue on GitHub
