// SPDX-License-Identifier: LGPL-2.1-or-later

/***************************************************************************
 *   Copyright (c) 2011 Juergen Riegel <FreeCAD@juergen-riegel.net>        *
 *                                                                         *
 *   This file is part of the FreeCAD CAx development system.              *
 *                                                                         *
 *   This library is free software; you can redistribute it and/or         *
 *   modify it under the terms of the GNU Library General Public           *
 *   License as published by the Free Software Foundation; either          *
 *   version 2 of the License, or (at your option) any later version.      *
 *                                                                         *
 *   This library  is distributed in the hope that it will be useful,      *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU Library General Public License for more details.                  *
 *                                                                         *
 *   You should have received a copy of the GNU Library General Public     *
 *   License along with this library; see the file COPYING.LIB. If not,    *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,         *
 *   Suite 330, Boston, MA  02111-1307, USA                                *
 *                                                                         *
 ***************************************************************************/


#pragma once

#include <App/PropertyStandard.h>
#include <App/PropertyLinks.h>
#include <App/SuppressibleExtension.h>
#include <Mod/Part/App/PartFeature.h>
#include <Mod/Part/App/PreviewExtension.h>
#include <Mod/PartDesign/PartDesignGlobal.h>

class gp_Pnt;
class gp_Pln;


/// Base class of all additive features in PartDesign
namespace PartDesign
{

using TopoShape = Part::TopoShape;

class Body;

/** PartDesign feature
 *   Base class of all PartDesign features.
 *   This kind of features only produce solids or fail.
 */
class PartDesignExport Feature: public Part::ShapeFeature,
                                public App::SuppressibleExtension,
                                public Part::PreviewExtension
{
    PROPERTY_HEADER_WITH_OVERRIDE(PartDesign::Feature);

public:
    Feature();

    /// Base feature which this feature will be fused into or cut out of
    App::PropertyLink BaseFeature;
    /// Transient memo of the nearest downstream Body marker for this feature (CPART_DESIGN
    /// §9). NOT a stored membership: it is Prop_Transient, never serialised, and always
    /// re-derivable from the BaseFeature chain via Body::findBodyOf. The name is legacy;
    /// read it as a cache of the reverse lookup, not as a body this feature belongs to.
    App::PropertyLinkHidden _Body;

    /// Keep a copy of suppressed shapes so that we can restore them (and maybe display them)
    Part::PropertyPartShape SuppressedShape;

    App::DocumentObjectExecReturn* recompute() override;
    App::DocumentObjectExecReturn* recomputePreview() override;

    short mustExecute() const override;

    /// Check whether the given feature is a datum feature
    static bool isDatum(const App::DocumentObject* feature);

    /// Returns the body the feature is in, or none
    Body* getFeatureBody() const;

    /**
     * Returns the BaseFeature property's object (if any)
     * @param silent if couldn't determine the base feature and silent == true,
     *               silently return a nullptr, otherwise throw Base::Exception.
     *               Default is false.
     */
    virtual Part::ShapeFeature* getBaseObject(bool silent = false) const;
    /// Returns the BaseFeature property's shape (if any)
    virtual const TopoDS_Shape& getBaseShape() const;
    /// Returns the BaseFeature property's TopoShape (if any)
    Part::TopoShape getBaseTopoShape(bool silent = false) const;

    // Fills up information about which sub-shapes were generated by the feature
    virtual void getGeneratedShapes(
        std::vector<int>& faces,
        std::vector<int>& edges,
        std::vector<int>& vertices
    ) const;

    virtual void updatePreviewShape();

    PyObject* getPyObject() override;

    const char* getViewProviderName() const override
    {
        return "PartDesignGui::ViewProvider";
    }

    void onChanged(const App::Property* prop) override;

    /// Called by Body::removeObject() when this feature's BaseFeature is
    /// rerouted around a deleted feature. Subclasses may reroute only the
    /// subelement links that are known to follow BaseFeature.
    virtual void onBaseFeatureRerouted(App::DocumentObject* oldBase, App::DocumentObject* newBase);

    App::DocumentObject* getSubObject(
        const char* subname,
        PyObject** pyObj,
        Base::Matrix4D* pmat,
        bool transform,
        int depth
    ) const override;


protected:
    static int countSolids(const TopoDS_Shape&, TopAbs_ShapeEnum type = TopAbs_SOLID);
    static bool relinkToMatchingSubelements(
        App::PropertyLinkSub& link,
        App::DocumentObject* oldBase,
        App::DocumentObject* newBase
    );

    /**
     * Fix solids
     */
    TopoShape fixSolids(const TopoShape&);

    void updateSuppressedShape();

    /**
     * Set the Material To Body Material object
     */
    void setMaterialToBodyMaterial();

    /// Grab any point from the given face
    static const gp_Pnt getPointFromFace(const TopoDS_Face& f);
    /// Make a shape from a base plane (convenience method)
    static gp_Pln makePlnFromPlane(const App::DocumentObject* obj);
    // TODO: Toponaming April 2024 Deprecated in favor of TopoShape method.  Remove when possible.
    static TopoDS_Shape makeShapeFromPlane(const App::DocumentObject* obj);
    static TopoShape makeTopoShapeFromPlane(const App::DocumentObject* obj);
};

using FeaturePython = App::FeaturePythonT<Feature>;

}  // namespace PartDesign
